// GENERATED by scripts/gen-brain-versions.ts — do not edit by hand.
// Run `npm run brain:versions` after changing a prompt, a tool schema, or a model id.
//
// 12 hex chars of SHA-256 over the static text that defines each brain (see brain-source.ts).
// Stamped onto every section the brain produces, so a stored Finding can be joined back to the
// reasoning that wrote it. tests/unit/brain-versions.test.ts fails if this has drifted from the
// live prompts.

export const BRAIN_VERSIONS: Record<string, string> = {
  "core": "e3e7a50f77cd",
  "chat": "c3bbde7b76a4",
  "persona-kodi": "2fef6017d62e",
  "aiOnPlan": "ced2aba1fdec",
  "allergyResults": "eac95b49d150",
  "diseaseResults": "5279fa1271d0",
  "familyResults": "92c357b71399",
  "hypothesisEvaluation": "78fe766f5c95",
  "noteResults": "1bfc137f17e1",
  "studyResults": "259c50a22404",
  "treatmentAssessment": "56147e9bd5e2",
  "treatmentGroups": "c18d22485692",
};
