// Product identity + Foundation copy, vendored from the pre-migration @tars/brand package (which
// stays in plover-code, still shared there with apps/tinytars — see the migration plan). This app
// no longer has a sibling to share it with, so it's local source rather than a re-exported package.
// User-facing copy is governed by apps/BRANDING.md.
import { deriveLegalLinks, type LegalLink } from "@tinytars/frame/brand";

export const PRODUCT_NAME = "LexiTar";
export const PRODUCT_TAGLINE = "Health Literacy Utility";
export const PRODUCT_TITLE = `${PRODUCT_NAME} — ${PRODUCT_TAGLINE}`;
export const PRODUCT_DESCRIPTION =
  "LexiTar translates lab jargon, maps biomarker reference ranges, and helps you prepare for doctor visits. Educational use only — not medical advice, diagnosis, or treatment.";

export const FOUNDATION_NAME = "Tiny Tars Foundation";
export const FOUNDATION_STATUS =
  "Tiny Tars Foundation is a registered 501(c)(3) public charity. EIN: 39-2278196.";

// The legal pages are routes on the tinytars site (non-discrimination/terms/privacy), served
// under the Foundation domain. This app is on a different origin, so it links absolutely
// (LEGAL_LINKS = LEGAL_BASE + path).
export const LEGAL_BASE = "https://tinytars.foundation";

// Verbatim from the audited tinytars health-literacy page (AUDIT.md criteria 2–4 PASS). Single
// source so the wording that passed compliance can't drift between the public site and dashboard.
export const MEDICAL_DISCLAIMER =
  "LexiTar is a public health literacy utility and educational resource intended solely to support " +
  "patient self-advocacy and improve communication between patients and their healthcare providers. " +
  "LexiTar does not provide medical advice, professional diagnostics, symptom triage, or treatment " +
  "recommendations. The information, biomarker reference translations, and physician preparation scripts " +
  "generated by this tool are for educational purposes only. Always consult a qualified, licensed " +
  "physician or healthcare professional regarding any medical condition, laboratory results, or changes " +
  "to your health regimen. Never disregard professional medical advice or delay seeking it because of " +
  "something you read or generate on this platform.";
export const PRIVACY_STATEMENT =
  "Your health privacy is paramount. LexiTar utilizes industry-standard end-to-end encryption to secure " +
  "your dashboard data. In strict compliance with Google Ad Grant policies and patient privacy standards, " +
  "we maintain a zero-commercial-advertising environment. We do not use tracking cookies for personalized " +
  "medical remarketing. As a donor-supported public asset, we never sell, rent, or monetize your personal " +
  "or health data to third-party advertisers, pharmaceutical companies, or data brokers.";

export type { LegalLink };

export const LEGAL_PATHS: LegalLink[] = [
  { path: "/non-discrimination", label: "Non-discrimination" },
  { path: "/terms", label: "Terms of Service" },
  { path: "/privacy", label: "Privacy Policy" },
];

// Absolute variant for consumers off the Foundation origin (the dashboard).
export const LEGAL_LINKS = deriveLegalLinks(LEGAL_BASE, LEGAL_PATHS);
