// LexiTar product identity + the Tiny Tars Foundation's org identity. Values live here, not in
// @tinytars/frame, which ships only their shape. User-facing copy is governed by apps/BRANDING.md.
import type { OrgIdentity } from "@tinytars/frame/brand";

export const PRODUCT_NAME = "LexiTar";
export const PRODUCT_TAGLINE = "Health Literacy Utility";
export const PRODUCT_TITLE = `${PRODUCT_NAME} — ${PRODUCT_TAGLINE}`;
export const PRODUCT_DESCRIPTION =
  "LexiTar translates lab jargon, maps biomarker reference ranges, and helps you prepare for doctor visits. Educational use only — not medical advice, diagnosis, or treatment.";

// The legal pages are routes on the Foundation site, a different origin from this app, so links
// are absolute (legalBase + path).
export const FOUNDATION: OrgIdentity = {
  name: "Tiny Tars Foundation",
  status: "Tiny Tars Foundation is a registered 501(c)(3) public charity. EIN: 39-2278196.",
  legalBase: "https://tinytars.foundation",
  legalPaths: [
    { path: "/non-discrimination", label: "Non-discrimination" },
    { path: "/terms", label: "Terms of Service" },
    { path: "/privacy", label: "Privacy Policy" },
  ],
};

// Verbatim from the audited tinytars health-literacy page (AUDIT.md criteria 2–4 PASS). Single
// source so the wording that passed compliance can't drift between the public site and dashboard.
export const MEDICAL_DISCLAIMER =
  "LexiTar is a public health literacy utility and educational resource intended solely to support " +
  "patient self-advocacy and improve communication between patients and their healthcare providers. " +
  "LexiTar does not provide medical advice, professional diagnostics, symptom triage, or treatment " +
  "recommendations. The information, biomarker reference translations, and physician preparation scripts " +
  "generated by this tool are for educational purposes only. Always consult a qualified, licensed " +
  "physician or healthcare professional regarding any medical condition, laboratory results, or changes " +
  "to your health regimen. Never disregard professional medical advice or delay seeking it because of " +
  "something you read or generate on this platform.";
export const PRIVACY_STATEMENT =
  "Your health privacy is paramount. LexiTar utilizes industry-standard end-to-end encryption to secure " +
  "your dashboard data. In strict compliance with Google Ad Grant policies and patient privacy standards, " +
  "we maintain a zero-commercial-advertising environment. We do not use tracking cookies for personalized " +
  "medical remarketing. As a donor-supported public asset, we never sell, rent, or monetize your personal " +
  "or health data to third-party advertisers, pharmaceutical companies, or data brokers.";

// DPG 9A.6 — what leaves the deployment, and where it is used. Disclosure rather than a per-patient
// consent switch (CORPUS.md §7): the documents are what make the answers worth having, so a
// half-informed answer is worse than an informed one. Four facts are the non-obvious ones and none is
// softened — the send happens on open rather than on asking, the copy outlives the session, there is
// no negotiated zero-retention agreement to point at, and whether it happens at all is the operator's
// setting (`REPORTS`) rather than the user's. That last clause is why the text says "when it is on":
// a deployment running REPORTS: "never" sends no document anywhere, and a notice claiming otherwise
// would be as false as one that stayed silent. Kept in step with SECURITY.md's processor table and the
// Foundation's published privacy policy — three texts that disagree are worse than none.
export const MODEL_DISCLOSURE =
  "Answering questions about your records means sending the reports themselves — whole documents, not " +
  "summaries — to the company that runs the language model behind those answers. Whoever operates this " +
  "deployment chooses whether that happens at all, and which company it is: with it off, no document ever " +
  "leaves. With it on, the documents go when you open a record, not only when you ask a question, and a " +
  "copy stays in the provider's prompt cache for up to about an hour after you stop using it — expiring on " +
  "the provider's schedule, which we can neither shorten nor recall. Read-aloud text goes to a separate " +
  "speech provider, on that provider's own terms. The model calls run on standard commercial terms, with " +
  "no negotiated zero-retention arrangement. The privacy policy names the companies in use today and what " +
  "each one's terms actually cover. Nothing goes to an advertiser, ever.";

// DPG 9B.4/9B.5 — who answers a safety report and how fast. Audited copy, and here rather than in the
// dialog because MODERATION.md, the report control and the Foundation's published policy all state it:
// three texts that disagree about a response time are worse than none.
//
// A role at the accountable organisation, not an individual's name: 9B.4 asks who answers for the
// service, which is the Foundation, and a personal name in published copy would have to be reissued
// every time the holder changes while adding nothing a reporter can act on.
export const SAFETY_OWNER = "the Tiny Tars Foundation's safety contact";
export const SAFETY_RESPONSE =
  "A person reads every report. We aim to acknowledge within 3 business days and to resolve within 10; " +
  "reports of illegal material are looked at within 1 business day.";
