// LexiTar product identity + the Tiny Tars Foundation's org identity. Values live here, not in
// @tinytars/frame, which ships only their shape. User-facing copy is governed by apps/BRANDING.md.
import type { OrgIdentity } from "@tinytars/frame/brand";

export const PRODUCT_NAME = "LexiTar";
export const PRODUCT_TAGLINE = "Health Literacy Utility";
export const PRODUCT_TITLE = `${PRODUCT_NAME} — ${PRODUCT_TAGLINE}`;
export const PRODUCT_DESCRIPTION =
  "LexiTar translates lab jargon, maps biomarker reference ranges, and helps you prepare for doctor visits. Educational use only — not medical advice, diagnosis, or treatment.";

// The legal pages are routes on the Foundation site, a different origin from this app, so links
// are absolute (legalBase + path).
export const FOUNDATION: OrgIdentity = {
  name: "Tiny Tars Foundation",
  status: "Tiny Tars Foundation is a registered 501(c)(3) public charity. EIN: 39-2278196.",
  legalBase: "https://tinytars.foundation",
  legalPaths: [
    { path: "/non-discrimination", label: "Non-discrimination" },
    { path: "/terms", label: "Terms of Service" },
    { path: "/privacy", label: "Privacy Policy" },
  ],
};

// Verbatim from the audited tinytars health-literacy page (AUDIT.md criteria 2–4 PASS). Single
// source so the wording that passed compliance can't drift between the public site and dashboard.
export const MEDICAL_DISCLAIMER =
  "LexiTar is a public health literacy utility and educational resource intended solely to support " +
  "patient self-advocacy and improve communication between patients and their healthcare providers. " +
  "LexiTar does not provide medical advice, professional diagnostics, symptom triage, or treatment " +
  "recommendations. The information, biomarker reference translations, and physician preparation scripts " +
  "generated by this tool are for educational purposes only. Always consult a qualified, licensed " +
  "physician or healthcare professional regarding any medical condition, laboratory results, or changes " +
  "to your health regimen. Never disregard professional medical advice or delay seeking it because of " +
  "something you read or generate on this platform.";
export const PRIVACY_STATEMENT =
  "Your health privacy is paramount. LexiTar utilizes industry-standard end-to-end encryption to secure " +
  "your dashboard data. In strict compliance with Google Ad Grant policies and patient privacy standards, " +
  "we maintain a zero-commercial-advertising environment. We do not use tracking cookies for personalized " +
  "medical remarketing. As a donor-supported public asset, we never sell, rent, or monetize your personal " +
  "or health data to third-party advertisers, pharmaceutical companies, or data brokers.";
