import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { discoverRoutes } from "../server/routes";

// Generates functions/_lib/route-patterns.ts from the functions/ tree, so an error report can name
// the route it came from without ever carrying a live pathname. Run via `npm run gen:routes`;
// tests/unit/route-patterns.test.ts regenerates and compares, so adding a route without
// regenerating fails CI rather than silently reporting "(unmatched)".

const APP = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const OUT = join(APP, "functions/_lib/route-patterns.ts");

export function patternsFor(functionsRoot: string): string[] {
  return discoverRoutes(functionsRoot).map(
    (r) => "/" + r.segments.map((s) => (s.kind === "static" ? s.value : s.kind === "param" ? `:${s.name}` : `:${s.name}*`)).join("/"),
  );
}

export function renderModule(patterns: string[]): string {
  return [
    "// GENERATED by scripts/gen-route-patterns.ts — do not edit. Run `npm run gen:routes`.",
    "//",
    "// A report names the PATTERN, never the pathname it came from: `/api/raw/alex/labs-2025.pdf`",
    "// identifies a patient and a document, `/api/raw/:path*` is code. The static segments here are",
    "// also the allowlist that scrubServerMessage() uses to decide which path tokens may survive.",
    "",
    "export const ROUTE_PATTERNS: readonly string[] = [",
    ...patterns.map((p) => `  ${JSON.stringify(p)},`),
    "];",
    "",
  ].join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(OUT, renderModule(patternsFor(join(APP, "functions"))));
  console.log(`wrote ${OUT}`);
}
