// Regenerates src/lib/brain-versions.ts. Run `npm run brain:versions` after changing any prompt text,
// tool schema, or model id, exactly as you would regenerate the prompt goldens.
//
// Why a COMMITTED map rather than hashing at runtime: the stamp has to be applied inside
// mergeLeafResult, which is synchronous and sits on the save path, and the browser's only SHA-256 is
// async. Precomputing also makes a brain change a reviewable line in a diff instead of a number that
// silently moves — which is the whole point of versioning it.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { sha256hex12 } from "@pablotech/neuro/hash-node";
import { brainSourceFor, brainKeys } from "../src/lib/brain-source";

export function brainVersions(): Record<string, string> {
  return Object.fromEntries(brainKeys().map((k) => [k, sha256hex12(brainSourceFor(k))]));
}

export function renderModule(versions: Record<string, string>): string {
  const rows = Object.entries(versions).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`);
  return [
    "// GENERATED by scripts/gen-brain-versions.ts — do not edit by hand.",
    "// Run `npm run brain:versions` after changing a prompt, a tool schema, or a model id.",
    "//",
    "// 12 hex chars of SHA-256 over the static text that defines each brain (see brain-source.ts).",
    "// Stamped onto every section the brain produces, so a stored Finding can be joined back to the",
    "// reasoning that wrote it. tests/unit/brain-versions.test.ts fails if this has drifted from the",
    "// live prompts.",
    "",
    "export const BRAIN_VERSIONS: Record<string, string> = {",
    ...rows,
    "};",
    "",
  ].join("\n");
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const versions = brainVersions();
  writeFileSync(fileURLToPath(new URL("../src/lib/brain-versions.ts", import.meta.url)), renderModule(versions));
  process.stdout.write(`wrote ${Object.keys(versions).length} brain versions to src/lib/brain-versions.ts\n`);
}
